allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
overrides:
  '@babel/core': '>=7.29.1'
  postcss: '>=8.5.18'
  sharp: '>=0.35.0'
minimumReleaseAgeExclude:
  - '@clerk/backend@3.13.2'
  - '@clerk/nextjs@7.6.2'
